### ISSUE TITLE
index is undefined

### ISSUE THREAD

**Issue by webhelpdesk2527** [alvarotrigo/multiscroll.js#100]
i was trying to use afterLoad but its giving me "index is undefined" error message in console.

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction of the issue in jsfiddle or codepen. 
I was not able to reproduce it in this demo: http://jsfiddle.net/kYU6d/4/

Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
