### ISSUE TITLE
Split content to 2 section?

### ISSUE THREAD

**Issue by okstmtcc** [alvarotrigo/multiscroll.js#101]
Hi! I am just wondering can this plugin split the content into 2 section? 

Example the footer section of this page:
https://www.ovolohotels.com.au/ovolowoolloomooloo/
The last part of this page will combine to one. 

Can I know is this achievable? Thanks!

**Comment by alvarotrigo** [comment]
That's not part of the library but of the developer himself.
The site you linked is using MultiScroll.js, so clearly it is possible but it is not something multiScroll.js provides in any of its features.

**Comment by okstmtcc** [comment]
Oh...okay. Thanks for the reply!

**Comment by okstmtcc** [comment]
Hi, just to check with you again. Is this site https://www.ovolohotels.com.au/ovolowoolloomooloo/ actually buying the license from you https://gumroad.com/l/multiscrollResponsiveExpand  to achieve the normal scrolling? Or is the developer achieve this by themselves?

Can make the split scroll become 1 page scrolling by using the existing plugin ?

**Comment by alvarotrigo** [comment]
> Is this site https://www.ovolohotels.com.au/ovolowoolloomooloo/ actually buying the license from > you https://gumroad.com/l/multiscrollResponsiveExpand to achieve the normal scrolling? Or is the developer achieve this by themselves?

Not for me to check :) I'm here to provide support for multiscroll issues, bugs and questions regarding the library. 

> Can make the split scroll become 1 page scrolling by using the existing plugin ?

Of course, haven't you seen the [multiscroll responsive expand extension](http://alvarotrigo.com/multiScroll/extensions/responsive-expand.html)?
