### ISSUE TITLE
Link redirects to fourth slide on page load (mobile only)

### ISSUE THREAD

**Issue by ashleighmm** [alvarotrigo/multiscroll.js#102]
On mobile only, when going to a page it redirects to the fourth slide on load on 3 of my pages. 
https://www.ventureweb.com/services/staffing/

Has anyone else had this issue?

**Comment by alvarotrigo** [comment]
I'm not able to reproduce it on the [demo page](https://alvarotrigo.com/multiScroll/).

Please provide an isolated reproduction as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

Use empty sections if possible and no CSS or JS files externals to multiScroll.js
