### ISSUE TITLE
Doesn´t work - Am I a dullard?

### ISSUE THREAD

**Issue by spaszwerg** [alvarotrigo/multiscroll.js#103]
Hi Alvaro,
I downloaded the package (multiscroll.js-master) an hour ago and its not working.
Just unzipped it and looked at the examples.
On all pages the scrolling events throw errors.
```
TypeError: MS.moveSectionDown is not a function - jquery.multiscroll.js:543:21
TypeError: MS.moveSectionUp is not a function - jquery.multiscroll.js:548:21
```
I didn´t change any file. Just unzipped it.
Pretty sure I´m missing something! But what?

Kind regards, Christoph

**Comment by alvarotrigo** [comment]
LOL.
I'm definitely the dullard one :) 

I fixed it now, releasing a new version 0.2.0 now.

**Comment by alvarotrigo** [comment]
Try now

**Comment by spaszwerg** [comment]
Jep, works like a charm!
Thank you
