### ISSUE TITLE
Compatibility with fullPage.js

### ISSUE THREAD

**Issue by johnnydevs** [alvarotrigo/multiscroll.js#104]
Is multiscroll.js compatible with fullPage.js ?

I'd like to have a few full screen slides, then some split screen slides, then some more full screen slides.

For example;

```
section 1 - full screen vertical slides
section 2 - multi scroll vertical slides
section 3 - full screen horizontal slides
section 4 - multi scroll vertical slides
```
I know this is probably possible using css, just wondering if there's another way?

Thanks

**Comment by alvarotrigo** [comment]
> Is multiscroll.js compatible with fullPage.js ?

You can try to use it, but it is not meant to be used together. 
So, it might work in some cases, such as using a single instance of fullPage.js in a single multiscroll panel. But it won't work in many other cases.

You might also find bugs during the implementation. 

So, basically. Use it at your own risk. I do not provide support for such feature.

**Comment by johnnydevs** [comment]
Thanks for the reply. I'd rather not pay for something that might not work. 

I'll find something else :)

**Comment by alvarotrigo** [comment]
> Thanks for the reply. I'd rather not pay for something that might not work.

multiScroll and fullpage.js are both free anyways :)
