### ISSUE TITLE
"scrollDelay" is not included in the options

### ISSUE THREAD

**Issue by abhijitparida** [alvarotrigo/multiscroll.js#107]
The `scrollDelay` variable which defines the delay to take place before being able to scroll to the next section is currently not available in the options.

**Comment by alvarotrigo** [comment]
And it shouldn't be :) 
Using a smaller value will cause issues in kinetic scrolling devices. 

I'll probably follow the same approach I did on [fullpage.js](https://alvarotrigo.com/fullPage/) and pagePiling.js.

Which doesn't require a delay, but instead detects when the scroll is accelering or not.
