### ISSUE TITLE
not working anymore on smartphones

### ISSUE THREAD

**Issue by smokingweb** [alvarotrigo/multiscroll.js#110]
Hello,
just to warn you that the split-scroll feature is not working anymore on smartphones (tested on Chrome and Safari).

I published a project at the end of May, and all worked fine, tested on various devices. Now it is not.

I checked your demo page, which is not working either.

Cannot say if it related to browser or Os updates.

Thanks!

**Comment by alvarotrigo** [comment]
Yeap thanks for reporting it! 
I have it on my to-do list!

**Comment by smokingweb** [comment]
Thanks Alvaro.
Did you spot out what the problem is?
Can you tell how much time will it take to be fixed?

Unfortunately in the very next days I have to decide whether to remake my project from scratch or wait for the fix. Any insight will be much appreciated!

Thanks again!

**Comment by alvarotrigo** [comment]
> Unfortunately in the very next days I have to decide whether to remake my project from scratch or wait for the fix. Any insight will be much appreciated!

Probably won't be fixed until start of August.

**Comment by alvarotrigo** [comment]
Fixed on multiScroll 0.2.2!!
