### ISSUE TITLE
Jump to slide without cross all others

### ISSUE THREAD

**Issue by tiago258** [alvarotrigo/multiscroll.js#114]
Hi,

I would like to know if it's possible, for example, jump from first slide to last slide without cross all other sliders.

Do you think it would be possible to implement?

Thanks,
Tiago

**Comment by alvarotrigo** [comment]
Sure set speed to 0. Scroll to whatever you want. Then set speed back to normal:
Use the method `$.fn.multiscroll.setScrollingSpeed(700);`

**Comment by tiago258** [comment]
Ok, thanks
