### ISSUE TITLE
scrollOverflow is not working

### ISSUE THREAD

**Issue by xtaaaal** [alvarotrigo/multiscroll.js#115]
This is my demo site, and after following the example html structure, the right side overflow content is not working.

http://socoldoutside.net/

**Comment by alvarotrigo** [comment]
You have to remove the layer you have over the whole content. For some reason you have an `after` layer on your body element.

Add this to your css:

```css
body:after{
display:none;
}
```

**Comment by xtaaaal** [comment]
After I remove the body after style, the overflowscroll does work, however the 1st right hand side section is not showing when website init. It only shows after the 3nd right side section are scrolled to be shown & scroll back to the 1st slide.
