### ISSUE TITLE
Finish content then only move to another section

### ISSUE THREAD

**Issue by khookeiwai** [alvarotrigo/multiscroll.js#116]
I have a long article in the left panel in section 2, how to create the website after scroll to the end then only move to section 3? I tried to create an internal scroll bar but not working.

![untitled-1](https://user-images.githubusercontent.com/30516072/53466064-52786d80-3a8b-11e9-9290-349b7754f051.jpg)

**Comment by alvarotrigo** [comment]
You would need to acquire the [scrollOverflow extension for multiscroll](https://alvarotrigo.com/multiScroll/extensions/scrollOverflow.html).
