### ISSUE TITLE
Callbacks (onLeave) not working?

### ISSUE THREAD

**Issue by spaszwerg** [alvarotrigo/multiscroll.js#117]
Hi Alvaro,
I´m struggeling to get the callbacks working. After several tests with different files, I took your current master and tried to get it working with your examples.
Doesn´t work there too!

I uploaded the contents of your master to my webspace and just changed the example.html file in the example folder.
I added the example code from the docs to the jQuery logic.
```js
$(document).ready(function() {
            $('#myContainer').multiscroll({
            	sectionsColor: ['#1bbc9b', '#4BBFC3', '#7BAABE'],
            	anchors: ['first', 'second', 'third'],
            	menu: '#menu',
            	navigation: true,
            	navigationTooltips: ['One', 'Two', 'Three'],
            	loopBottom: true,
            	loopTop: true,
				onLeave: function(index, direction){
					//after leaving section 2
					if(index == '2' && direction =='down'){
						alert("Going to section 3!");
					}
					else if(index == '2' && direction == 'up'){
						alert("Going to section 1!");
					}
				}
            });
        });
```

Whats my mistake?

Very looking forward to hear from you.
All the best, Chris
[
http://dev.schuetz-mediendesign.de/multiscroll/examples/example.html](http://dev.schuetz-mediendesign.de/multiscroll/examples/example.html)

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in jsfiddle.net or codepen.io with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by spaszwerg** [comment]
Hi Alvaro,
a good article, thanks!
Here is the fiddle: [https://jsfiddle.net/schuetzmedia/drugtb47/3/](https://jsfiddle.net/schuetzmedia/drugtb47/3/)

**Comment by alvarotrigo** [comment]
You are missing the `nextIndex` param in the function params.
Those have to be in order as in any other JS function :)

```js
onLeave: function(index, nextIndex, direction){
```

Demo online:
https://jsfiddle.net/39rfvz65/

**Comment by spaszwerg** [comment]
I see ;o)
Would it make sense to alter the example in the docs for better understanding?

Thanks a lot!

**Comment by alvarotrigo** [comment]
> Would it make sense to alter the example in the docs for better understanding?

Uh! Totally! I didn't notice the mistake there :)

Would you like to commit a pull request for it?

**Comment by spaszwerg** [comment]
I´m honestly not that familliar with github ;o)

**Comment by alvarotrigo** [comment]
No worries! I've done it myself now :)
