### ISSUE TITLE
Possible to have a div above?

### ISSUE THREAD

**Issue by benjaminthedev** [alvarotrigo/multiscroll.js#121]
Hi Álvaro,

Thank you for multiscroll!
I have a question, can you have a div above multiscroll?  In the docs I see you can have header and footer but I want to create my own div.

Cheers, 
Ben.

**Comment by alvarotrigo** [comment]
I don't see why not. Use the magic of CSS :)
I would encourage you to ask in another place such as stackoverflow.com where they'll be able to help you much better.
