### ISSUE TITLE
Is it possible to use only one botton to get to the next slide pair?

### ISSUE THREAD

**Issue by ballmannweber** [alvarotrigo/multiscroll.js#123]
I love this script but I am looking for a solution to use only one button (!) to get through all slide pairs without the possibilty to choose individual pairs. is this possible?

**Comment by alvarotrigo** [comment]
Sure!
See the methods moveSectionDown and moveSectionUp
https://github.com/alvarotrigo/multiscroll.js#methods

**Comment by ballmannweber** [comment]
thanks for the lightning fast response :-) 
I must have overseen this option while browsing the docs. 

can you give me short example how to use…
$.fn.multiscroll.moveSectionUp()
with a button with the id "next"?

I have some problems constructing the js call… sorry.

**Comment by alvarotrigo** [comment]
```js
$('#next').click(function(){
    $.fn.multiscroll.moveSectionUp()
});
```

**Comment by ballmannweber** [comment]
thank you :-)
