### ISSUE TITLE
keep on scrolling rest of the page after last section

### ISSUE THREAD

**Issue by ersenturgut** [alvarotrigo/multiscroll.js#124]
Hi
I found your multiscroll and it is very nice...I want to use it at the top of my webpage...is it possible to keep scrolling rest of the page after last section? in your example.html page I added a div after mycontainer has a height 2000px for example...when I scrolled mutlscroll last (third) section I want to go down rest of my page...is it possible???

of course when user scroll up to top of my page multscroll must work reverse to first section...

thanks...

**Comment by alvarotrigo** [comment]
Unfortunately that's not an option provided by multiScroll.js at the moment.

**Comment by ersenturgut** [comment]
ok...is it possible to use multscroll in the first section of fullpage?

**Comment by alvarotrigo** [comment]
I don't know, I've never tried it :) 
Give it a try and let me know!

**Comment by ersenturgut** [comment]
ok I am waiting for your answer...I can use my rest of the page as second section of fullpage...in first section of fullpage I can use multiscroll...

**Comment by alvarotrigo** [comment]
No, I mean, you can try it by yourself and let me know if it works. 
I'm not going to try :)

**Comment by ersenturgut** [comment]
ok forget it...

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/multiscroll.js/issues/49
