### ISSUE TITLE
Can't scroll past the slider to other section in mobile devices

### ISSUE THREAD

**Issue by sushilth94** [alvarotrigo/multiscroll.js#125]
I have used the multi scroll js in one of my website. But when I view it on mobile, I can't scroll past the slider to rest of the contents in the page. It works fine on desktop
https://fisher-staging.basehost.digital/

**Comment by alvarotrigo** [comment]
Can you reproduce the issue on the [demo page](https://alvarotrigo.com/multiScroll/)?

If not, then try to provide an isolated reproduction with no external CSS or JS to multiScroll and the less amount of HTML possible, with a single heading on each section.

**Comment by sushilth94** [comment]
Hi @alvarotrigo 

Thanks for the quick response. I have created a codepen with your demo example so that I can demonstrate my issue. Here is the link
https://codepen.io/axel_design/pen/MWbvorE

Basically, When I view the page on mobile, I am stuck on the slider part, I can't scroll to the other content section I have added. But it works fine on laptop browsers, going to other sections. Please check-in mobile

**Comment by sushilth94** [comment]
This version fixed the issue for me https://fisher-staging.basehost.digital/wp-content/themes/Divi-child/assets/js/multiscroll.js?ver=1.0 .So It's all good now. Thanks

**Comment by alvarotrigo** [comment]
Yeah, unfortunately multiScroll won't support any page that has content above or below the multiScroll wrapper.
