### ISSUE TITLE
move one slide per scroll

### ISSUE THREAD

**Issue by andreyc0d3r** [alvarotrigo/multiscroll.js#126]
Hi,

Just wondering if this plugin can allow me to move one slide per one scroll action. The next slide move should occur only after scrolling stopped.

**Comment by alvarotrigo** [comment]
> Just wondering if this plugin can allow me to move one slide per one scroll action.

Isn't this what is happening now? Can you elaborate it?

> The next slide move should occur only after scrolling stopped.

What do you mean?

**Comment by andreyatlas** [comment]
thank you for your reply.

For example, when im using macbook's touchpad to scroll, one swipe should take me to the next slide. Even if my swipe is exaggerated. At the moment, I have to be very cautions with how I swipe.

Lets say I have 5 slides, one big swipe on the touchpad, scrolls through all the slides without stopping. 

The desired behaviour would be, one swipe ( not matter how short or long the distance of the swipe) takes you to the next slide only.

Same applies to scroll wheel.

This site seems to have a desired effect

https://malmo.qodeinteractive.com/split-screen-slider

**Comment by andreyc0d3r** [comment]
@alvarotrigo  thank you for your reply.

For example, when im using macbook's touchpad to scroll, one swipe should take me to the next slide. Even if my swipe is exaggerated. At the moment, I have to be very cautions with how I swipe.

Lets say I have 5 slides, one big swipe on the touchpad, scrolls through all the slides without stopping.

The desired behaviour would be, one swipe ( not matter how short or long the distance of the swipe) takes you to the next slide only.

Same applies to scroll wheel.

This site seems to have a desired effect

https://malmo.qodeinteractive.com/split-screen-slider

**Comment by alvarotrigo** [comment]
This is an issue without a proper solution today. Kinetic scrolling devices will always have this issue.
We developers don't have ways of detecting the end of a kinetic swipe.

I won't get into detail now, but check out this issue https://github.com/alvarotrigo/fullPage.js/issues/1654.

> This site seems to have a desired effect
> 
> https://malmo.qodeinteractive.com/split-screen-slider

I've tested it and that page still fails when the swipe is very fast on kinetic scrolling devices.

**Comment by alvarotrigo** [comment]
As a solution, try using a slower speed.
1000 should be enough to prevent most of those fast scrolls.

**Comment by andreyc0d3r** [comment]
thank you for your reply, they should be some sort of debounce implemented that goes into effect until the next slide reached. 

either something like this: https://dannyvankooten.com/delay-scroll-handlers-javascript/
or
tracking the distance slider travelled from its original position
