### ISSUE TITLE
using multiscroll nested inside a component. Like a carousel

### ISSUE THREAD

**Issue by lukelehane** [alvarotrigo/multiscroll.js#130]
I have one full page where it works perfectly. On another page, I have a header banner that requires a similar functionality within it. a left image and a right image one side scrolls up one down.

Is there an in built way to use multiscroll for this? I'm thinking I can use the JS methods to make it 'auto scroll' on a timer, but the problem I have is that the multiscroll css adds overflow: hidden to the body tag so it doesn't seem like it's made for nesting in this way.

**Comment by alvarotrigo** [comment]
Unfortunately multiScroll only works on the page level. It's not designed to deal with non fullscreen situations.
