### ISSUE TITLE
Mobile responsiveness

### ISSUE THREAD

**Issue by lukelehane** [alvarotrigo/multiscroll.js#131]
I've successfully made this responsive myself by turning everything off below a certain point. As well as destroying the events at a certain screen size, I've had to add !important CSS to overwrite the overflow: hidden and height: 100% on the body and html tag. This works fine in Google Inspect but the page does not scroll on an iphone. Are you able to tell me why this is? Is there some other div with these rules being applied on a phone?

Many many thanks,

Luke.

**Comment by alvarotrigo** [comment]
multiScroll provides a [Responsive Expand extension](https://alvarotrigo.com/multiScroll/extensions/responsive-expand.html) to deal with responsiveness. 

Unfortunately, we do not provide support for anything else that is not provided by the plugin out of the box.
