### ISSUE TITLE
Multiscroll in shopify theme

### ISSUE THREAD

**Issue by ecourdoisy** [alvarotrigo/multiscroll.js#133]
Hello,

I'm trying to use multiscroll in my shopify theme. Ive added .js and .css and then add script to launch multiscroll but always have error about multiscroll is not a function. I don't understand because script is load before launch.

Do you know if i can use it in Shopify ?

Thanks a lot

**Comment by alvarotrigo** [comment]
> Do you know if i can use it in Shopify ?

I haven't used Shopify. But I assume it is? :)

**Comment by alvarotrigo** [comment]
I'd recommend you to ask in shopify communities.
