### ISSUE TITLE
Loading script

### ISSUE THREAD

**Issue by ecourdoisy** [alvarotrigo/multiscroll.js#134]
Hello, 

I'm using multiscroll script on my website, I'have a loading bug. At the first load of the page I've "Uncaught TypeError: t(...).multiscroll is not a function" error, if I reload, it's ok ! 

In my head I have
```
<script
	src="https://code.jquery.com/jquery-3.6.0.min.js"
	integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
	crossorigin="anonymous"></script>
<script src="{{ 'jquery.multiscroll.js' | asset_url }}"></script>
<script src="{{ 'jquery.easings.min.js' | asset_url }}"></script>
  <script src="{{ 'custom.js' | asset_url }}" async></script>
```
  

Can you help me ?

**Comment by alvarotrigo** [comment]
Sure, can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/) or [codepen](https://codepen.io/alvarotrigo/pen/WNpwPLJ), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by ecourdoisy** [comment]
I can't do this because when I put the script only in html file it's ok, seems to be link to the loading of all scripts :(

**Comment by alvarotrigo** [comment]
Unfortunately, I can't help then.
