### ISSUE TITLE
Keyboard issue

### ISSUE THREAD

**Issue by erropix** [alvarotrigo/multiscroll.js#14]
When I scroll down using keyboard the section slide partially
![alvarotrigo_com_multiscroll_ second](https://cloud.githubusercontent.com/assets/6576868/4086881/a00de73c-2f41-11e4-9dc1-f9215089f349.png)

**Comment by dheil** [comment]
for me this wouldn't be a bug, but a feature, would it be possible to implement that behaviour as an optional feature? i want the scrolling effect to slide partially if i use the arrow keys on the keyboard.
