### ISSUE TITLE
Sections exclussions

### ISSUE THREAD

**Issue by marekka** [alvarotrigo/multiscroll.js#140]
Hi it's not  bug but rather a pre-buy question.
Can I combine standard and no scroll sections, for instance:
<div>Standard section 1</div>
<div id="multiscroll">
	<div class="ms-left">
		<div class="ms-section">1</div>
		<div class="ms-section">2</div>
		<div class="ms-section">3</div>
	</div>
	<div class="ms-right">
		<div class="ms-section">💪</div>
		<div class="ms-section">😊</div>
		<div class="ms-section">🥳</div>
	</div>
</div>
<div>Standard section 2</div>

**Comment by alvarotrigo** [comment]
Unfortunately that's not something provided by multiScroll.js
