### ISSUE TITLE
AOS compatibility

### ISSUE THREAD

**Issue by marekka** [alvarotrigo/multiscroll.js#141]
Hi, is there an option to make it compatible with https://michalsnik.github.io/aos/ or any other similar library?

**Comment by alvarotrigo** [comment]
multiScroll.js doesn't use scrollBar so anything relying completely on it won't be compatible with it.

See if AOS allow you to specify other properties to replace the scroll top value. 

But I would encourage you to make use of multiScroll callbacks to trigger custom animations instead. 
See the example here:
https://github.com/alvarotrigo/multiscroll.js/blob/master/examples/callbacks.html
