### ISSUE TITLE
Multiscroll.js license

### ISSUE THREAD

**Issue by cercleagence** [alvarotrigo/multiscroll.js#142]
Hi !
I've bought a WP template with DroitThemes.
They needed to uploade saasland.core. Since, their is a red etiquette "Unlicensed Multiscroll.js Entension " on my Home page, as you can see on screenshot attached.

How to remove it please ?

<img width="1004" alt="Capture d’écran 2023-05-09 à 11 12 11" src="https://user-images.githubusercontent.com/132999614/237058753-cff62a2c-57e8-41b2-b7ba-30b5fca850ae.png">

**Comment by alvarotrigo** [comment]
Did you buy a license for the multiScroll extension you are using?
You can get a license here:
https://alvarotrigo.com/multiScroll/extensions/

Then you have to activate the license as per the instructions you'll get by email and in the docs:
https://github.com/alvarotrigo/multiscroll.js#use-extensions
