### ISSUE TITLE
Website doesn't upload on Chrome, Firefox. Very slow on Safari

### ISSUE THREAD

**Issue by cercleagence** [alvarotrigo/multiscroll.js#143]
Hi !
I'be bought template with DroitThemes.
Saasland

Mywebsite doesn't upload at all on Firefox.
On Chrome it's very slow. On Safari too.

What kind of problems could it be . Thanks a lot

**Comment by alvarotrigo** [comment]
I have no idea.
I don't even know what DroitThemes is :) 

We'll help you with any question regarding multiScroll.js usage, but anything outside it is not within our competences so I'd recommend you ask the creators of your theme.
