### ISSUE TITLE
Is there anyway to enable auto scrolling after specified time ? 

### ISSUE THREAD

**Issue by shumailxyz** [alvarotrigo/multiscroll.js#22]
Is there anyway to enable auto scrolling after specified time ? So the it automatically slides to the next section after specified amount of time ?

**Comment by BobIMG** [comment]
Sorry for opening an old thread....we're not finding a way to achieve an auto scroll after a specified amount of time. Do we have a code conflict on our end (is this supported currently by the project)?

**Comment by alvarotrigo** [comment]
> is this supported currently by the project

It should work if you do it in the way I said in the 1st answer.
