### ISSUE TITLE
Not able to make any entry in the form fields.

### ISSUE THREAD

**Issue by RanganathKieon** [alvarotrigo/multiscroll.js#25]
Hi,

I have used the Multiscroll.js in my site and also have a contact form, but i am not able to make any entry in the form fields.

thanks
Ranga

**Comment by alvarotrigo** [comment]
Can you provide a link with the reproduction of the problem?

**Comment by conair355** [comment]
Hi,

Please check this link http://designzealstudio.net/test/index.html

**Comment by alvarotrigo** [comment]
Download the latest version.
