### ISSUE TITLE
about setAllowScrolling and others methods

### ISSUE THREAD

**Issue by talgautb** [alvarotrigo/multiscroll.js#28]
there are no such method ? but what here - [Readme](https://github.com/alvarotrigo/multiscroll.js#setallowscrolling)

p.s. i added `destroy` and `build` methods, i can do PR. Also i want ask about minify for js ? which you use ?

**Comment by alvarotrigo** [comment]
Yeah, probably I mistake in the readme. It shouldn't be there.

> Also i want ask about minify for js ? which you use ?

[Closure](http://closure-compiler.appspot.com/home) with default settings
