### ISSUE TITLE
IE8 minified error 0.1.5

### ISSUE THREAD

**Issue by darith27** [alvarotrigo/multiscroll.js#31]
Bug: The minified js file results in an error in IE8. 

Solution: Using a the Closure compiler creates a working minified version for IE8.

http://closure-compiler.appspot.com/home

**Comment by alvarotrigo** [comment]
Which problem is it? The plugin was minified using closure compiler.

**Comment by darith27** [comment]
![screen shot 2015-02-26 at 1 38 31 pm](https://cloud.githubusercontent.com/assets/3331878/6400170/ce5c5fce-bdbc-11e4-9418-26ce866b6e07.png)

**Comment by alvarotrigo** [comment]
Oh right, that's because they are not really the same version.
Feel free to commit the pull request with the new minified version.

**Comment by alvarotrigo** [comment]
I'll check it probably tomorrow.

**Comment by alexgleason** [comment]
@alvarotrigo Thanks for replying so fast! You're awesome man. (I'm on the same team as Darith btw). Just sent you a donation.

**Comment by alvarotrigo** [comment]
Thanks @alexgleason ;) 
I would solve it now, but I have no access to IE 8 from here and that complicates the process. So I'll tell you tomorrow about the fix.

**Comment by alvarotrigo** [comment]
I don't see any error in the demo page. 
It sounds like a problem with your HTML markup.

Could you reproduce the problem somewhere where I can access to it?
Or post the HTML markup somewhere>
