### ISSUE TITLE
Height for table is not calculated correctly

### ISSUE THREAD

**Issue by katindo** [alvarotrigo/multiscroll.js#34]
First of all thank you for the great plugin!

I have installed it in one of my websites and it's working great except one problem.

When you land on the page everything is really zoomed it. If you resize a bit the browser window it goes back to normal.

After, searching I noticed that the height of "ms-tableCell" is assigned to 4374px instead of 529px that it should be.

I haven't mess with your js or css. I only adjusted my html and css.

Any idea what could have caused this error?

Kat

**Comment by katindo** [comment]
On a second look I think I know what causes the problem.
I have changed the "vertical-align" to "top" for some sections/pages.

Is there a way to make it work by keeping the valign set to "top"?

**Comment by alvarotrigo** [comment]
Make sure you are not missing the compulsory DOCTYPE declaration at the start of your page:
I'm using `<!DOCTYPE html>` in all my examples, but you can use any other doctype. 

Without any link or way to reproduce your problem I'm afraid I can not help you much more on it.

**Comment by katindo** [comment]
Hello @alvarotrigo ! Thank you for the quick response.
I cannot post a link here.
Is there a way to contact you via email?

Kat

**Comment by alvarotrigo** [comment]
Yeah, through my website: http://alvarotrigo.com/
