### ISSUE TITLE
Vertical Scroll

### ISSUE THREAD

**Issue by jensychen** [alvarotrigo/multiscroll.js#37]
Hello, 
I am using the scrolling example to build a site that is a horizontal scrolling site, so there is a scroll bar to accommodate any content that is longer than the defined height of the page. Since the up/down keys were originally set to scroll vertically between sections, I can't use them to scroll down/up content within one section. How can I change that? 

I've also noticed that the content the content does not scroll on mobile devices. Can you suggest a fix please?

Thank you,
Jen

**Comment by alvarotrigo** [comment]
> Since the up/down keys were originally set to scroll vertically between sections, I can't use them to scroll down/up content within one section. How can I change that?

You can't.


> I've also noticed that the content the content does not scroll on mobile devices. Can you suggest a fix please?

Which content? The scrollable content you created? Are you using `normalScrollElements` for it?
