### ISSUE TITLE
Clone navigation

### ISSUE THREAD

**Issue by yorock** [alvarotrigo/multiscroll.js#39]
Hello, 
I am currently using your multiscroll.js for a personal project and I want to know if there is any issue to have both left and right navigation (with tooltip) with different tooltip content ?

Thank you for your answer,
yorick

**Comment by alvarotrigo** [comment]
Well, the issues is that multiScroll doesn't provide any option to do so. You'll have to do it by yourself.

**Comment by yorock** [comment]
Ok :)
