### ISSUE TITLE
Change scroll direction

### ISSUE THREAD

**Issue by Michkkael** [alvarotrigo/multiscroll.js#40]
Hello !
I'm using multiscroll for a project. Pictures/Videos are on the left side and my main content is on the right side. So, when the user is scrolling, the main content moves down. 
Is there any way to change this behavior ? Like change the scroll direction.

Thanks !

**Comment by alvarotrigo** [comment]
The plugin doesn't provide any option for it.
But if you really need it, [let me know](http://alvarotrigo.com/#contact-page) and I can customize the plugin for you.

**Comment by Michkkael** [comment]
Ho yes ! It could be very great :)

**Comment by afincato** [comment]
I would also be interested in this option, but more in the sense of changing the scroll direction at a certain breakpoint. Would that be possible?

How did it work for Michkkael?

Thanks,
André

**Comment by camilawaz** [comment]
@Michkkael are you working great with videos? 
I'm using in a project, but the video (html5 tag) don't autoplay :(

**Comment by Michkkael** [comment]
Yes ! 
I use a video which is autoplaing/stopping on a project. (when your leave the slide of the video, the video stops)

For this, I use callbacks of multiscroll.js.

See my code :
 html :

<video id="videoBG" autoplay loop poster="<?php echo get_stylesheet_directory_uri(); ?>/assets/videos/polina.jpg">
	<source src="<?php echo get_stylesheet_directory_uri(); ?>/assets/videos/polina.webm" type="video/webm">
	<source src="<?php echo get_stylesheet_directory_uri(); ?>/assets/videos/polina.mp4" type="video/mp4">
</video>

js :

//events
onLeave: function(index, nextIndex, direction){
	if (index == '1') {
		$('video#videoBG').css("opacity", "0");
		document.getElementById("videoBG").pause();
	}
},
afterLoad: function(anchorLink, index){
	if (index == '1') {
		$('#prevSlide').addClass('inactive');
		$('video#videoBG').css("opacity", "1");
		document.getElementById("videoBG").play();
	}
}


index is 1 because the video slide is the frist one :)

'Hope it helped you !

**Comment by Michkkael** [comment]
html :

<video id="videoBG" autoplay loop poster="<?php echo get_stylesheet_directory_uri(); ?>/assets/videos/polina.jpg">
	<source src="<?php echo get_stylesheet_directory_uri(); ?>/assets/videos/polina.webm" type="video/webm">
	<source src="<?php echo get_stylesheet_directory_uri(); ?>/assets/videos/polina.mp4" type="video/mp4">
</video>

js :

//events
onLeave: function(index, nextIndex, direction){
	if (index == '1') {
		$('video#videoBG').css("opacity", "0");
		document.getElementById("videoBG").pause();
	}
},
afterLoad: function(anchorLink, index){
	if (index == '1') {
		$('#prevSlide').addClass('inactive');
		$('video#videoBG').css("opacity", "1");
		document.getElementById("videoBG").play();
	}
}


index is 1 because the video slide is the frist one :)

'Hope it helped you !

**Comment by camilawaz** [comment]
@Michkkael I'll try your solution soon! Hope it works for me! 
Thank you so much

**Comment by Michkkael** [comment]
Np !
Keep me informed ;)

**Comment by stevethorson** [comment]
Reversing the direction of the panels is as easy as just flipping the left one to the right side and the right one to the left side. You can do it by adding this bit of css to your code:
`.ms-right{left:0 !important}`
`.ms-left{right:1px !important}`
That will reorder the UI for you, then you just need to go into your html and swap the class names so that your content appears on the side that you want.

**Comment by bhargavgandhi** [comment]
@stevethorson 
Thank you so much buddy for the quick fix. I did tried and it worked :)
Only small add to this below:
```
.ms-right{
    left:0 !important;
    right: initial !important;

}
.ms-left{
    right:1px !important;
    left: initial !important;
}
```

Thanks!
