### ISSUE TITLE
Turn off the plugin under a certain screen size

### ISSUE THREAD

**Issue by Le-future** [alvarotrigo/multiscroll.js#41]
Hi there!

Firstly, thank you so much for providing a great plugin like this one!

So, what I need is to, under a certain resolution, stop the plugin and when you go back to a higher resolution, re-activate it.

I've tried with $(window).resize(function() { but without success... :-(

This is why I'm asking a start of solution to you :-)

Thank you for your patience and your amazing job!

**Comment by alvarotrigo** [comment]
Use the `resize` option for it.

**Comment by alvarotrigo** [comment]
Sorry, I though you were speaking about fullPage.js.

There's no way now to do it. The plugin doesn't provide any way to do it.
If you really need it, [contact me](http://alvarotrigo.com/#contact-page) to ask for a customization.

**Comment by Le-future** [comment]
Alright, no problem ;-)

I'm trying to do it with the CSS, I've almost find a solution for having a good layout on mobile, tablet...

Sorry, I'm not a real jQuery Pro ^^ and there is not a solution, external to the plugin to "kill it" when the window is resize and pass through the resolution and re-activate it when you go the opposite road?

Best

**Comment by alvarotrigo** [comment]
There's no external solution I'm afraid.

**Comment by Le-future** [comment]
Eww ^^

In fact, with the CSS I can display perfectly the content on small devices but only the left part.

The plugin continues to do his job smoothly but the right sections are logically not displayed.

**Comment by alvarotrigo** [comment]
I have nothing else to say I'm afraid.

**Comment by Le-future** [comment]
Ok, I'm going to try to find the best solution, thanks!

**Comment by alvarotrigo** [comment]
You can use `$.fn.multiscroll.multiscroll.destroy();` to destory the evens. Then you would have to deal with the CSS styles, wrappers and so on.

**Comment by Le-future** [comment]
I tried to implement it in my code but the plugin is going weird :smile: 

What is wrong here : 

<pre><code>$(document).ready(function($) {

    $(window).resize(function() {

        if ($(window).width() < 1280) {
            $.fn.multiscroll.multiscroll.destroy();
        }
        
        else {
        $('#multi-div').multiscroll({
            // sectionsColor: ['#FFF', '#FFF', '#FFF'],
            anchors: ['first', 'second', 'third', 'fourth'],
            menu: '#menu',
            navigation: true,
            navigationTooltips: ['Welcome', 'About', 'Newsletter', 'Map'],
            loopTop: true,
            loopBottom: true
        });
    }
});</code></pre>

**Comment by talgautb** [comment]
@Le-future do you find solution ?
may be you should use `$.fn.multiscroll.multiscroll.destroy()` and `$.fn.multiscroll.multiscroll.build();` ?

**Comment by Le-future** [comment]
@talgautb for the moment I've stopped to try something, I'm still at the point mentionned in my last message.

the build function can works with this plugin?

**Comment by talgautb** [comment]
@Le-future update plugin, i added `destroy` and `build` functions #30 
something like that ?
```
$(document).ready(function(){

  $('#multi-div').multiscroll({
    // your config for plugin
  });

  function toggleMs() {
    if ($(window).width() <= 1280) {
      $('#multi-div').multiscroll.destroy();
    } else {
      $('#multi-div').multiscroll.build();
    }
  }

  $(window).resize(function(){
    toggleMs(); // check to destroy or build when we resize browser
  });
});
```

**Comment by Le-future** [comment]
@talgautb Very interesting mate :+1: 

I'm gonna test your solution asap, I keep you posted :-)

**Comment by Le-future** [comment]
@talgautb Done a test a few minutes ago and WOW, what a nice surprise, under 1280px the plugin is well disabled and re-activated when you resize the window up to 1280px, congrats man!

That's almost perfect, the small "black point" is when you load the page in for example a window of 1200px for the wdth, the plugin remains activated, you have to resize the window to disable it, any idea to disable it immediately when the window is already under 1280px?

**Comment by talgautb** [comment]
@Le-future just init function when page load:
```
$(document).ready(function(){

  $('#multi-div').multiscroll({
    // your config for plugin
  });

  function toggleMs() {
    if ($(window).width() <= 1280) {
      $('#multi-div').multiscroll.destroy();
    } else {
      $('#multi-div').multiscroll.build();
    }
  }
  // check when page load
  toggleMs();  // NEW

  $(window).resize(function(){
    toggleMs(); // check to destroy or build when we resize browser
  });
});
```

**Comment by Le-future** [comment]
I thought to have tested with toggleMs when page load but visibly no :smile: 

Works perfectly @talgautb , I'm very grateful to you for having helped me with this trick!

**Comment by talgautb** [comment]
@Le-future :smile: 
about order - there is no such method in plugin, so you should do it yourself
p.s. if that all, can you close issues ?)

**Comment by Le-future** [comment]
Alright, thanks so much mate :smiley: 

close

**Comment by talgautb** [comment]
oops ) Do you have button 'Close issues' ?
or it can do @alvarotrigo

**Comment by Le-future** [comment]
Hey @talgautb , sorry to reopen the issue but I think it's better to ask my question here,

When I load the page with a size higher than 1280 px and I reduce it under the 1280px it's impossible to scroll, the "scroll anchor" is well disabled but I can't scroll normally as a simple page. I don't have the problem if I load the page with a size under the 1280px.

And last question, do you think is possible to set the order of the sections with jQuery under the 1280px?

Thanks so much for your help :smiley:

**Comment by Le-future** [comment]
Regarding the order for the div under 1280px, I get a solution but almost good :+1: 

```
$(document).ready(function(){

    function OrderDiv() {
        if ($(window).width() <= 1024) {
            $("#right1").insertAfter("#left1");
            $("#right2").insertAfter("#left2");
            $("#right3").insertAfter("#left3");
            $("#right4").insertAfter("#left4");
        } else {
            $('#multi-div').multiscroll.build(); // I don't know what to write here
        }
      }
      // check when page load
      OrderDiv(); 

      $(window).resize(function(){
        OrderDiv(); 
      });
});
```

When you load with a screen size bigger than 1280px, no problem the multiscroll is on, you resize your screen under 1280px, the order of the div is well modified as I need.

But when you load under 1280px or resize up to 1280px, the multiscoll seems to be dead ^^

**Comment by Le-future** [comment]
@talgautb @alvarotrigo Hi guys, just a small question, this part : 
// check when page load
  toggleMs();  // NEW

Provoke this error : TypeError: f.handler.apply is not a function

how could I solve this, can't find a solution

**Comment by talgautb** [comment]
@Le-future hard to say) may be if we'll see all script

**Comment by Le-future** [comment]
@talgautb thanks for your answer, how can I show you all script here?

You need multiscroll.js and my main js file where I start the plugin?
