### ISSUE TITLE
navigation don't show

### ISSUE THREAD

**Issue by karafarinweb** [alvarotrigo/multiscroll.js#42]
hi,
i use multi scroll in my web site but navigation don't show;

http://takceram.co.ir/new/index.php/%DA%AF%D8%A7%D9%84%D8%B1%DB%8C-%D8%AA%D8%B5%D8%A7%D9%88%DB%8C%D8%B1

my code is 

jQuery('#myContainer').multiscroll({
        anchors: ['1st', '2nd', '3nd','4st', '5nd', '6nd','7st', '8nd', '9nd','10st'],
                loopTop: true,
                 loopBottom: true,
                navigation: true,
                  navigationColor: '#000',
                navigationTooltips:['1st', '2nd', '3nd','4st', '5nd', '6nd','7st', '8nd', '9nd','10st'],
                navigationPosition: 'right',
           scrollingSpeed: 1700
          });

tanx

**Comment by talgautb** [comment]
@karafarinweb hi! can't find menu. do you use menu's markup ? look [here](https://github.com/alvarotrigo/multiscroll.js#options) read about `menu`

**Comment by shishta** [comment]
Hello here, 
even though I have set 
$('#multiscroll').multiscroll({
            menu: false,
            navigation: true,
            loopTop: true,
            loopBottom: true
        });
the navigation is not showing.

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in jsfiddle or codepen, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by shishta** [comment]
> Can you please provide an isolated reproduction in jsfiddle or codepen, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

https://fisher.basehost.digital/#
I am trying to use this on a DIVI builder elements. The slider is working completely fine but the only issue is it doesn't throw that
" multiscroll-nav" after the main slider even though the navigations is set true. Is this because I'm using a builder?

**Comment by alvarotrigo** [comment]
Hi @shishta , I would need an isolated reproduction, this is, a page with the minimum amount of HTML and no external CSS or JS to multiScroll.js.

Also, multiScroll is not suppose to be used in a non full-screen page.
