### ISSUE TITLE
right side loads late

### ISSUE THREAD

**Issue by yogendrakarekar** [alvarotrigo/multiscroll.js#43]
Hi Alvaro,

I must say gr8 plugin
but I think the right side lags.

I am trying to use this plugin with bootstrap for a website. I have used a fullscreen carousel and I used the solution described in this site http://reverzo.tymberry.com/ to do so.

My problem is that i am trying to make a full screen carousel by taking two carousel on left and right side which cuts and looks as one.

This is my site http://tantra-gyan.in/nitpl/#first

The carousel is not synched well and right side lags.

**Comment by alvarotrigo** [comment]
I do not see any problem, but as I told you by  mail, use `css3:true` to speed it up.

**Comment by yogendrakarekar** [comment]
I tried this but its still not working here is my code

**Comment by yogendrakarekar** [comment]
$('#multiscroll').multiscroll({
         easing: 'easeInOutSine',
         navigationColor: 'orange',
         navigation: true,
         css3: true,
         navigationTooltips: ['Indictrans', 'GIS', 'ERPNext', 'Clientele', 'Testimonials', 'Awwards', 'Contact'],
         anchors: ['first', 'second', 'third', 'fourth', 'fifth', 'sixth', 'seventh']
    });
