### ISSUE TITLE
Disable animations

### ISSUE THREAD

**Issue by explotter** [alvarotrigo/multiscroll.js#44]
Thanks for this beautiful plugin.

How can I disable slide animation and 50% width for phones?

Thanks.

**Comment by alvarotrigo** [comment]
You can only [destroy](https://github.com/alvarotrigo/multiscroll.js#destroy) the plugin if you dont need it.

**Comment by explotter** [comment]
Thank you. How can I disable only in low screen sizes?

I try this but didn't work:

    <script>
        if ($(window).width() < 480) {
                $.fn.multiscroll.multiscroll.destroy();
        }
    </script>
