### ISSUE TITLE
How to perform code after $.fn.multiscroll.moveTo has finished

### ISSUE THREAD

**Issue by JoshuaNovak919** [alvarotrigo/multiscroll.js#47]
How can I execute code after `$.fn.multiscroll.moveTo(1)` has finished? I'm using `multiscroll` in conjunction with `fullpagejs` and I need to have `multiscroll` go to the top and when it is finished have `fullpagejs` go to the top.

**Comment by JoshuaNovak919** [comment]
I ended up adding in a callback option that could be passed. It may be a good idea to add this at some point or have it return a promise.

**Comment by talgautb** [comment]
@JoshuaNovak919 may be https://github.com/alvarotrigo/multiscroll.js#onleave-index-nextindex-direction ?

**Comment by alvarotrigo** [comment]
Use the callbackas as @talgautb  pointed out.
