### ISSUE TITLE
Destroy Event

### ISSUE THREAD

**Issue by csergiuu** [alvarotrigo/multiscroll.js#51]
Hey guys, 

I'm trying to destroy/build plugin while resizing browser, but it doesn't work at all, does anyone know if this event work properly ?

Cheers,

**Comment by alvarotrigo** [comment]
It only destroy the plugin events:

> Destroy plugin's events.

**Comment by csergiuu** [comment]
Well, even after "$.fn.multiscroll.multiscroll.destroy();" it work properly

**Comment by alvarotrigo** [comment]
> $.fn.multiscroll.multiscroll.destroy();

Nop. It should be:

```
$.fn.multiscroll.destroy();
```

**Comment by alvarotrigo** [comment]
The documentation seems to be wrong. A mistake from the pull request of the guy who added the functionality.

**Comment by csergiuu** [comment]
Well tried that option too, and it still working :D

**Comment by alvarotrigo** [comment]
Reproduce it in jsfiddle or codepen.

**Comment by csergiuu** [comment]
http://codepen.io/anon/pen/GJPwam

**Comment by alvarotrigo** [comment]
You are using  a very old version of multiscroll.
Use the latest 0.1.7 instead of 0.0.6.

**Comment by csergiuu** [comment]
Well, where can I get the latest version?

Thanks :+1:

**Comment by csergiuu** [comment]
thanks for "support" ...

**Comment by alvarotrigo** [comment]
Not in your codepen...
http://codepen.io/anon/pen/GJPwam

**Comment by alvarotrigo** [comment]
Right. There's something wrong there. To be honest I never tested it after the pull request. 
I'll take a look in like a week or two. Currently on holidays.

**Comment by csergiuu** [comment]
Ok, thank you! 

Have a nice holidays!

**Comment by talgautb** [comment]
we need tests :) @alvarotrigo

**Comment by alvarotrigo** [comment]
@talgautb feel free to provide some in a pull request :) 
I'm not having much time lately. And fullpage.js is taking much of my time.

**Comment by talgautb** [comment]
@alvarotrigo i found problem in demo http://codepen.io/anon/pen/GJPwam
@csergiuu used multiscroll.js 0.1.4 Beta from [here](http://alvarotrigo.com/multiScroll/jquery.multiscroll.min.js) and there is no such events
problem fixed :) ?!

**Comment by alvarotrigo** [comment]
> @csergiuu used multiscroll.js 0.1.4 Beta from here and there is no such events
> problem fixed :) ?!

Yep, exactly. The events exist in 0.1.7. Not in 0.1.4.

**Comment by csergiuu** [comment]
Actually I used v 0.1.7.

**Comment by alvarotrigo** [comment]
> Actually I used v 0.1.7.

Your codepen was using 0.1.4 until today that I've uploaded the latest versions to the site.

**Comment by talgautb** [comment]
@csergiuu can you find `build` event [here](http://alvarotrigo.com/multiScroll/jquery.multiscroll.min.js) ?!)

**Comment by alvarotrigo** [comment]
> @csergiuu can you find build event here ?!)

>  I've uploaded the latest versions to the site.
