### ISSUE TITLE
Question: Incorporate slides from your fullPage.js?

### ISSUE THREAD

**Issue by reddo** [alvarotrigo/multiscroll.js#52]
Hi. Is it possible to incorporate the slides functionality above the current split-screen from your fullPage.js script? I'd need to use those in addition to the current scroll, with the hash updates included.

Thanks for your time.

**Comment by alvarotrigo** [comment]
> the slides functionality above the current split-screen

What's that?

**Comment by reddo** [comment]
I need a section to scroll horizontally in addition to vertically. Line the slides in your fullScreen.js (http://alvarotrigo.com/fullPage/#secondPage/1)

**Comment by alvarotrigo** [comment]
Sorry the plugin doesn't provide any way to do it.
