### ISSUE TITLE
enhancement

### ISSUE THREAD

**Issue by talgautb** [alvarotrigo/multiscroll.js#56]
what about `gulp` (to build plugin);
`eslint` (for codestyle),
`sass` with `autoprefixer` for css ?
maybe something else ?!
@alvarotrigo

**Comment by alvarotrigo** [comment]
Feel free to add a pull request.


> sass with autoprefixer for css ?

If you add a SASS stylesheet, then it should be the result of the CSS one. Not the other way around.
I work with CSS directly as this is such a small stylesheet.

**Comment by talgautb** [comment]
- [x] `gulp`
- [ ] `eslint` ? for styleguide
- [ ] `mocha` fro test
