### ISSUE TITLE
responsive 

### ISSUE THREAD

**Issue by 4him** [alvarotrigo/multiscroll.js#61]
Hello, I was very impressed by this plugin and it's good opportunity for using in different projects. I have small question I did some changes in project but I don't think it should influences at responsive mode. Is this plugin responsive, I mean ready for tablet and phones using or not?
Thanks for your work.

**Comment by alvarotrigo** [comment]
Duplicated https://github.com/alvarotrigo/multiscroll.js/issues/23

It doesn't provide a way to remove the auto scrolling and the 2 panels if that's what you mean.

**Comment by 4him** [comment]
Sorry for duplicate. I mean 2 sections and menu?

**Comment by alvarotrigo** [comment]
It doesn't provide any option at all.
