### ISSUE TITLE
Combining full page with multiscroll page

### ISSUE THREAD

**Issue by justawebbie** [alvarotrigo/multiscroll.js#62]
Is it possible to alternate between a full width page of content with the multiscroll content and keep navigation running smoothly between the content?

I would like to do one or two left to rights with multiscroll then go to a full page, then back to the left to right multiscroll content.  I hope I am making sense.

**Comment by alvarotrigo** [comment]
Nop, that's not possible.

**Comment by justawebbie** [comment]
Shoot, thank you for the fast reply.  Do you know of a script that can do both by chance?

**Comment by alvarotrigo** [comment]
Nop sorry. What you can do is use an absolute positioned element in one of the sides and set the width to 200%.
