### ISSUE TITLE
is it possible to dissociate ms-left and ms-right ?

### ISSUE THREAD

**Issue by fabiobonzini** [alvarotrigo/multiscroll.js#63]
on first scroll, ms-left dont move and ms-right move 1, 2 or 3 times, and conversely.

its possible with multiscroll.js ?

**Comment by alvarotrigo** [comment]
The plugin doesn't provide any option for it.

**Comment by fabiobonzini** [comment]
ok thanks for reactivity !

**Comment by alvarotrigo** [comment]
What you can try to do is having a fixed element on the left side. Then animate it by yourself to move it out of the viewport when necessary.
