### ISSUE TITLE
Destroy fuction

### ISSUE THREAD

**Issue by dngine** [alvarotrigo/multiscroll.js#64]
Great plugin, good job! Really like it but I have a small issue. At a certain breakpoint the two panels become to narrow so I use the destroy function to ... wel destroy the instance of the plugin. This works ok on desktop (i.e. I can scoll with the mouse), but on an iPhone (havent checked Android) the scolling event is still locked. I would asume the destroy function would reseverse all functionallity but maybe there's a good reason for the way it works now.

**Comment by alvarotrigo** [comment]
> maybe there's a good reason for the way it works now.

Not really. 
The destroy function was added thanks to @talgautb who provided it. It does the job for desktops but it doesn't for touch devices as you said.

**Comment by alvarotrigo** [comment]
If you really need it you can [contact me](http://alvarotrigo.com/#contact-page) for an urgent request.

**Comment by dngine** [comment]
Ok, I'll do that. Thanks for your quick reply.

**Comment by talgautb** [comment]
Good reason to add new PR :+1:  thx @dngine
