### ISSUE TITLE
Safari nav styling issue

### ISSUE THREAD

**Issue by redone75** [alvarotrigo/multiscroll.js#65]
Running into an interesting issue on the latest version of Safari when utilizing the navigation/anchor linking combo.

We're utilizing a light gold color (#c6943f) in the design for the border color. When scrolling through the panels, the color of the inactive dots are randomly turning blue.

I recreated the issue on your demo by updating the **#multiscroll-nav ul li a span** to the color above (both in fill and border) and are seeing the same issue there. Images below:

![multiscroll-safari-9-issue-css](https://cloud.githubusercontent.com/assets/9701826/12861508/c36c7fb6-cc18-11e5-9367-be26a61b3a0d.png)
![multiscroll-safari-9-issue-1](https://cloud.githubusercontent.com/assets/9701826/12861463/6a3be832-cc18-11e5-8573-348edbba356a.png)
![multiscroll-safari-9-issue-2](https://cloud.githubusercontent.com/assets/9701826/12861464/6d08f6f4-cc18-11e5-8e37-394075f8256c.png)

Any insight would be greatly appreciated. Safari accounts for 25% of our current desktop views for this project, so anxious to find a solve.

Thanks.

**Comment by alvarotrigo** [comment]
I can not reproduce the issue. Please create a jsfiddle or codepen where I can reproduce it.

**Comment by redone75** [comment]
This project went dormant for awhile, so this fell off my radar. It's back in play and the issue is still present. 

I recreated the issue by downloading the latest zip and updated the border of the #multiscroll-nav span to match our design. 

```
#multiscroll-nav span{
    border: 1px solid #c6943f;
}
```

You can see it in action within Safari 9.1 here:
http://redone.org/_dev/multiscroll/examples/example.html

As you'll scroll, you notice that the dot nav turns blue instead of staying the intended gold color. Maybe something to do with visited links?

**Comment by redone75** [comment]
Recorded a video showing the issue in action:
https://dl.dropboxusercontent.com/u/938980/multiscroll-safari.mp4

**Comment by alvarotrigo** [comment]
It seems to be a Safari issue.http://stackoverflow.com/questions/36330569/bug-in-safari-9-adding-blue-color-to-links-border

**Comment by alvarotrigo** [comment]
But having said that, I'm not able to reproduce it on the demo page on Safari 9.0. You can test it yourself in www.browserstack.com
