### ISSUE TITLE
Combination of two multiscroll and fullpage

### ISSUE THREAD

**Issue by 5PK** [alvarotrigo/multiscroll.js#67]
I'm trying to use the multiscroll feature for the first page of the site, but after that I want to use regular transitions from fullpage.js. I was wondering if this was at all possible

**Comment by alvarotrigo** [comment]
Not possible I'm afraid.

**Comment by milanagheda** [comment]
I have used. It's working fine

**Comment by FelipeKoblinger** [comment]
Hi, @milanagheda! Can you share how you did it? I'll be appreciated :)
Thanks

**Comment by milanagheda** [comment]
You can check here - http://carlsgarten.njudev.de/

**Comment by milanagheda** [comment]
hi @FelipeKoblinger  You can check here - http://carlsgarten.njudev.de/
