### ISSUE TITLE
Content show well only on resize

### ISSUE THREAD

**Issue by fmorancais** [alvarotrigo/multiscroll.js#69]
Hello.

Thank you for multiscroll, it's very beautiful and useful for what i wanted to do :)

But, I have a little problem, my page : http://www.dreyan.com/about is looking weird.
The content is not positioned well, and I don't know why. When i resize the window or open the developper tools, the content shows normally and I have the result I want.

I have never been exposed to that kind of issue..Do you have any solutions or at least a lead ?
Thank you !

![capture d ecran 2016-05-09 a 10 44 27](https://cloud.githubusercontent.com/assets/14920789/15107926/40553456-15d3-11e6-9423-458b4147491f.png)

**Comment by alvarotrigo** [comment]
If you believe it is a plugin's bug, please reproduce your issue in an isolated environment such as jsfiddle or codepen with no external CSS or JS.

**Comment by fmorancais** [comment]
I believe it's because of my CSS. The problem is my margin, when i don't put margin in my h1 (for example) the rendering is better.
So, I put a negative margin-top in my text content and it's better but not perfect. This is not the solution and seems not a clean fix imo.

Anyway, if this is the bug I will test different things on my side.

Thank you.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
