### ISSUE TITLE
JQuery error after destroy and build plugin

### ISSUE THREAD

**Issue by rocchidavide** [alvarotrigo/multiscroll.js#72]
In my code, on click I disable the plugin; on second click I re-enable it. I do it with destroy() and build().
But, after I build() the plugin, I obtain the follow error in console:

`jquery.min.js:3 Uncaught TypeError: f.handler.apply is not a function`

every time I go outside and inside the viewport with the mouse pointer.

**Comment by alvarotrigo** [comment]
There's no `build` function in fullpage.js so I've no idea what you are talking about. 

Can't help without an isolated reproduction. Try to reproduce your issue in jsfiddle or codepen. 
I'll close the issue until then.

**Comment by alvarotrigo** [comment]
Sorry, I didn't realise you were talking about multiscroll.js.
But still, provide a reproduction please.

**Comment by rocchidavide** [comment]
Here is an unfuddle [https://jsfiddle.net/drocchi/zL4mn72z/9](https://jsfiddle.net/drocchi/zL4mn72z/9/)

1) open the console
2) click on the viewport 
3) click on the viewport again
4) enter and exit inside the viewport with the mouse pointer, and look in the console in the meanwhile
