### ISSUE TITLE
add old version to npm package

### ISSUE THREAD

**Issue by maruilian11** [alvarotrigo/multiscroll.js#74]
hi, recently we want to add your lib to https://cdnjs.com, could you please consider adding old version of `multiscroll.js` to npm package so that we can use **npm auto-udpate** to add them (also for later new version) automatically to cdnjs.
thank you very mush!

https://github.com/cdnjs/cdnjs/issues/8795

**Comment by alvarotrigo** [comment]
What do you mean by "the old version"? 
Can't I just add the current one? v.0.1.7

**Comment by maruilian11** [comment]
I mean could you please also add v0.1.6, v0.1.5 and v0.0.4 to npm package, we can use auto-update config to add them to cdnjs. or it's ok if you don't want to do that, we will add them manually by ourself. thanks!

**Comment by maruilian11** [comment]
hi @alvarotrigo,
I already sent a PR to add old released version. 
To maintain the latest version on cdnjs, please remember to push new version to npm package when you release. :smiley:

**Comment by alvarotrigo** [comment]
@maruilian11 thanks for it!
