### ISSUE TITLE
Uncaught TypeError: MS.moveSectionDown is not a function

### ISSUE THREAD

**Issue by thehung2224** [alvarotrigo/multiscroll.js#75]
Hi,

I'm having problem with the plugin. I create new page only use Slider Revolution, however when I view on front page and I can't scroll down. In console log, I get this message:

> Uncaught TypeError: MS.moveSectionDown is not a function

How I can fix this issue? I'm using WP 4.5.3

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in jsfiddle or codepen with no external CSS or JS. 
I'll close the issue until then.
