### ISSUE TITLE
On Click js problem

### ISSUE THREAD

**Issue by AdityaMishra95** [alvarotrigo/multiscroll.js#76]
I have placed some images on the right side of the page and made the images open a modal on click using java script. But the click function is not working on the right hand side of the page.

It works perfectly fine on the left side but it is not working on the right hand side.

Please help its really urgent

**Comment by alvarotrigo** [comment]
If you believe its a bug please provide an isolated reproduction in jsfiddle or codepen.

> Please help its really urgent

If you need specific support feel free to [contact me](http://alvarotrigo.com/#contact-page) to contract my services.

**Comment by kevinvanderven** [comment]
Did you ever find a solution?

**Comment by alvarotrigo** [comment]
I was never able to reproduce the issue. I'll close this issue.
