### ISSUE TITLE
multiscroll.js with content that overflow the section

### ISSUE THREAD

**Issue by robmim** [alvarotrigo/multiscroll.js#78]
I want to know if its possible to use multiscroll.js on section with text that overflow the viewport like on this sample: https://jsfiddle.net/fidgeting/gpv8vwco/

So i want to activate the multiscroll. if the content text is bigger tant the viewport deactivate it to scroll the content. When at the bottom of the content reactivate the plugin and go to the next slide.

Is that possible ?

**Comment by alvarotrigo** [comment]
multiScroll.js doesn't provide such option I'm afraid.

**Comment by robmim** [comment]
Thanks

**Comment by GaelJaboulay** [comment]
You can use a DIV in the concerned page in which you put your content. That DIV should have CSS property "overflow:auto"

**Comment by alvarotrigo** [comment]
This is now possible thanks to the [ScrollOverflow Extension for multiscrol](https://alvarotrigo.com/multiScroll/extensions/scrollOverflow.html)
