### ISSUE TITLE
1px gap on some window sizes in Safari

### ISSUE THREAD

**Issue by sebszocinski** [alvarotrigo/multiscroll.js#8]
In some window sizes there is a 1px white gap in the middle of the screen... only in Safari on Mac (that i've tested) - any idea whats causing this? could it be a sub-pixel issue?

Screenie attached...

![image](https://cloud.githubusercontent.com/assets/5466694/3595629/11c1b57c-0cb8-11e4-8f79-f941df623536.png)

**Comment by yogendrakarekar** [comment]
Hi Alvaro,
but I think the right side lags.

I am trying to use this plugin with bootstrap for a website. I have used a fullscreen carousel and I used the solution described in this site http://reverzo.tymberry.com/ to do so.

My problem is that i am trying to make a full screen carousel by taking two carousel on left and right side which cuts and looks as one.

This is my site http://tantra-gyan.in/nitpl/#first

The carousel is not synched well and right side lags.
