### ISSUE TITLE
how to remove mousewheel scroll 

### ISSUE THREAD

**Issue by cvaraj** [alvarotrigo/multiscroll.js#81]
i want to use only by click function transition like next prev options but i don't want mousewheel scroll and keybord scroll how to stop this two function, when i set keuboard scrolling false, it will act as normal scroll, but i don't need that. is there any solution for that?.

**Comment by alvarotrigo** [comment]
You can use the undocumented function `$.fn.multiscroll.setMouseWheelScrolling(false)`.

**Comment by cvaraj** [comment]
thank you @alvarotrigo  its working.. nice script

**Comment by GaelJaboulay** [comment]
Thanks  @alvarotrigo, this work fine but responsive expand desactivates it if we resize the browser in a mobile size, then resize back to a bigger size.

**Comment by alvarotrigo** [comment]
Yes
