### ISSUE TITLE
IOS Orientation Change

### ISSUE THREAD

**Issue by MatthewGabriel** [alvarotrigo/multiscroll.js#84]
Hi,

First - thanks, great plugin.

Second - I am struggling to get this to work nicely on ios.  The issue seems to be related to the navigation / address bars that appear or disappear on ios when you change the orientation of the device.  It makes the position of the images offset from their correct position and can get progressively worse if you keep flipping the orientation.

This site which is how I came across multiscroll breaks on iPhone if you constantly flip between the portrait and landscape:

http://laludelo.com/

Anyone seen this before?

Thanks.

**Comment by MatthewGabriel** [comment]
This site which is how I came across multiscroll breaks on iPhone if you constantly flip between the portrait and landscape:

http://laludelo.com/

**Comment by talgautb** [comment]
hi! just use power of css with js event ;)

**Comment by MatthewGabriel** [comment]
@talgautb  Could you provide more information?
