### ISSUE TITLE
Autoplay option... has it?

### ISSUE THREAD

**Issue by tofanelli** [alvarotrigo/multiscroll.js#86]
Hello Alvaro!

how's going? Hope ok

Is there an autoplay option on Multiscroll? So it can applied in a small section (30vh 100vw) and works like a image gallery... 

is there a way to apply this?

Cheers =)

**Comment by alvarotrigo** [comment]
See this answer: http://stackoverflow.com/questions/28213764/automatic-scroll-using-multiscroll-js
