### ISSUE TITLE
Set height for Multiscroll

### ISSUE THREAD

**Issue by tofanelli** [alvarotrigo/multiscroll.js#87]
Hey Alvaro

quick question... i want to set the height for Multiscroll for 30vh for my viewport.. 

I already tried 

var windowHeight = $(window).height() * 0.3;

and already set in all "height" variables this same size.... does not work with % or px or vh.... 

And already set in a inline css for a section, but, no lucky at all... 

is there any way to accomplish this?

Cheers =)

**Comment by alvarotrigo** [comment]
I'm afraid I do not provide support for any modification, but check also the CSS is not interfering with it.
