### ISSUE TITLE
Link inside ms-section gets overridden by auto scroll in chrome

### ISSUE THREAD

**Issue by balticdesign** [alvarotrigo/multiscroll.js#89]
If I click on a link to another page displayed within the multiscroll panel Chrome starts loading the page and then cancels when the url is set to /#panel2.

In Firefox and other browsers this doesn't seem to happen.

Can I pause or destroy multiscroll  once a link has been clicked?

**Comment by alvarotrigo** [comment]
Can't really help without an isolated reproduction.

> Can I pause or destroy multiscroll once a link has been clicked?

Sure. Check [the destroy function](https://github.com/alvarotrigo/multiscroll.js#destroy).

**Comment by balticdesign** [comment]
Fast response :) I have my example here - not isolated though

https://stairpartsdirect.co.uk/

 I'm going to check the destroy function after link has been clicked

**Comment by alvarotrigo** [comment]
I just don't understand why a link should trigger any multiScroll action.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
