### ISSUE TITLE
multi-frame scrolling when using mouse wheel (in an Angular app?)

### ISSUE THREAD

**Issue by nextriot** [alvarotrigo/multiscroll.js#90]
Hi. Awesome plugin. Thanks for creating it.

EDIT: I originally posted a link to my implementation. After viewing a couple of your issue responses however I've created a JSFiddle displaying the same behavior: [https://jsfiddle.net/c567jj26/](https://jsfiddle.net/c567jj26/) - you'll need to click 'State 1' initially. 

So the issue I'm having is that on page load the plugin acts as expected, but if I then navigate to another link within the SPA and then go back to the home page (either by using the back button or link) the lightest touch of the mousewheel makes the plugin scroll to the last frame. If I use the keyboard buttons it jumps 2 frames.

I tried digging into the plugin code, and have only concluded that it may very well be an issue at the event level, because `MouseWheelHandler` gets called double the amount of times when navigating back to the home screen a second time.

Further, in 'State 2' in the fiddle you'll see that autoplay is pretty much random within the SPA.

Any help is very much appreciated. Thanks again.

**Comment by alvarotrigo** [comment]
> the lightest touch of the mousewheel makes the plugin scroll to the last frame.

It seems you are initializing multiScroll.js multiple times. Try to do it only once if the plugin was not initialized in any page before.
