### ISSUE TITLE
Feature Request responsive

### ISSUE THREAD

**Issue by mtompkins** [alvarotrigo/multiscroll.js#91]
While I may be mistaken, I do not think the following "feature" is currently easily implemented.

Considering responsive design and mobile device up, I think the ability to natively support these devices in the following manner would be a great addition. When instantiating the multiscroll.js, an option for `mobile: true` wherein left and right sections are virtually attached so scrolling would be in a standard fashion. That way we could have the split-screen effect on larger displays and then when the viewport becomes too qualitatively small for the effect, revert inherently to moving the left and right sections in tandem and in one direction.

Why not just skip instantiating multiscroll.js? Because it is likely we've provided some CSS around other elements of the solution that we would like to keep (e.g. navigation buttons)

**Comment by alvarotrigo** [comment]
I was [working on it the other day](https://twitter.com/IMAC2/status/851452646900805633).
I'll soon announce two new extensions for it:

- Responsive Expand:
    Auto scrolling will be turned off and each left and right panel will expand to take the 100% width of the viewport. The order will be able to be defined in the a `data` attribute. In case you want the right side to the shown before the left one.

- Responsive Combine
   Auto scrolling will be turned off and both sides, left and right of each section, will be combined into a single section moving at the same time, as a single block. 

I expect to release it after Easter, around the 19th.

**Comment by mtompkins** [comment]
What a wonderful bit of news - congratulations on a really done solution!!

**Comment by alvarotrigo** [comment]
Oh, and both will get triggered by using the same options as in [fullpage.js](https://github.com/alvarotrigo/fullPage.js):

- responsiveWidth
- responsiveHeight

Same state classes and callbacks.

**Comment by alvarotrigo** [comment]
A new extension provides this feature! Check the [Responsive Expand extension](http://alvarotrigo.com/multiScroll/extensions/responsive-expand.html)

![apr 24 2017 12-12 pm](https://cloud.githubusercontent.com/assets/1706326/25334672/8592c1c8-28e7-11e7-82fe-85432f41eb8a.gif)

**Comment by mtompkins** [comment]
Congrats - looks fantastic.
