### ISSUE TITLE
Responsive Extension - Links not working

### ISSUE THREAD

**Issue by vianneylancres** [alvarotrigo/multiscroll.js#93]
Hi!

Thank you for the multiScroll plugin and also the responsive extension, that I bought three days ago.

I have created a menu navigation that works fine on desktop, but as soon as I am on a mobile screen, the links in my menu, are not working anymore - there are no errors.

I am also using a "scroll down" link that uses the "moveTo(slide)" function on click, which stops working on mobile aswell. Here I tried to add touch or touchstart which did not work either.

Any ideas on that one? Normal jumping to the href section would be ok, sliding even better...

Thank you!

**Comment by alvarotrigo** [comment]
Can you please [contact me ](http://alvarotrigo.com/#contact)with a URL I can check?

**Comment by jeffAwesome** [comment]
I'm having a very similar issue. We just purchased the plugin a few days ago as well.  The links are all out of whack on mobile.  I also get stuck in a recurring cycle... i cant scroll past a section... and on desktop at that same section the multiscroll gets out of sync.

**Comment by alvarotrigo** [comment]
As I said to the previous person:
Can you please [contact me](http://alvarotrigo.com/#contact) with a URL I can check?

**Comment by alvarotrigo** [comment]
Fixed!
