### ISSUE TITLE
Uncaught ReferenceError: lastScrolledDestiny is not defined

### ISSUE THREAD

**Issue by adamjw3** [alvarotrigo/multiscroll.js#98]
Getting the above error in chrome.

i'm using browserfy to bundle my js so in my packages.json i have the following

"browser": {
 
    "jquery.easings": "./src/libs/jquery.easings.min.js",
    "multiscroll": "./src/libs/jquery.multiscroll.js"
  },

Then in my js i'm doing 

`import "jquery.easings";
import "multiscroll";

var Home =
{
    "Init": function () {
        $("#multiscroll").multiscroll();
    },
};

module.exports = Home;`

any idea why this error is showing? seems to function fine even with it. thanks

Just to add to this, this error is stopping the navigation active class being removed and applied to the current slide.

**Comment by corey01** [comment]
I encountered this problem, the solution for me was to require the NPM library, instead of just importing the jquery.multiscroll.min.js from my vendor scripts folder.

**Comment by alvarotrigo** [comment]
Can you please provide a link with an isolated reproduction of the issue?

**Comment by alvarotrigo** [comment]
Fixed on the latest version multiScroll 0.2.3
